import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1738925678197 implements MigrationInterface {
    name = 'Init1738925678197'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "admin_captchas" ("id" BIGSERIAL NOT NULL, "equation" text NOT NULL, "answer" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + '00:10:00'), "is_active" boolean NOT NULL DEFAULT true, "admin_session_id" bigint, CONSTRAINT "PK_6fa15f13db1b66cc78edc7d73de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_captchas_pkey" ON "admin_captchas" ("id") `);
        await queryRunner.query(`CREATE TABLE "captchas" ("id" BIGSERIAL NOT NULL, "equation" text NOT NULL, "answer" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + '00:10:00'), "is_active" boolean NOT NULL DEFAULT true, "session_id" bigint, CONSTRAINT "PK_897703cbd18f8ee4d7ed8753adb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "captchas_pkey" ON "captchas" ("id") `);
        await queryRunner.query(`CREATE TABLE "email_verifications" ("id" BIGSERIAL NOT NULL, "token_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + '00:10:00'), "is_active" boolean NOT NULL DEFAULT true, "user_id" bigint, CONSTRAINT "UQ_7939cc2e493281f265179fa86ce" UNIQUE ("token_hash"), CONSTRAINT "PK_c1ea2921e767f83cd44c0af203f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "email_verifications_token_hash_key" ON "email_verifications" ("token_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "email_verifications_pkey" ON "email_verifications" ("id") `);
        await queryRunner.query(`CREATE TABLE "logs" ("id" BIGSERIAL NOT NULL, "status_code" text NOT NULL, "log_level" text NOT NULL, "short_description" text NOT NULL, "long_description" text, "debug_info" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "audit_type" text NOT NULL DEFAULT 'ASSERT', "admin_user_id" bigint, "user_id" bigint, CONSTRAINT "PK_fb1b805f2f7795de79fa69340ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "logs_pkey" ON "logs" ("id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" BIGSERIAL NOT NULL, "quantity" bigint NOT NULL, "unit_price" numeric(12,2) NOT NULL, "total_price" numeric(12,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "order_id" bigint, "product_id" bigint, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "order_items_pkey" ON "order_items" ("id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" BIGSERIAL NOT NULL, "payment_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" bigint NOT NULL, "payment_provider" text, "provider_payment_id" text NOT NULL, "paid_amount" numeric(12,2), "status" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d9eb3ee419efb34829c062d306d" UNIQUE ("payment_hash"), CONSTRAINT "UQ_b2f7b823a21562eeca20e72b006" UNIQUE ("order_id"), CONSTRAINT "REL_b2f7b823a21562eeca20e72b00" UNIQUE ("order_id"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "payments_payment_hash_key" ON "payments" ("payment_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "payments_order_id_key" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "payments_pkey" ON "payments" ("id") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" BIGSERIAL NOT NULL, "order_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" text NOT NULL, "paid_amount" numeric(12,2), "total_price" numeric(12,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "discount_percentage" numeric(5,2) NOT NULL DEFAULT 0, "vat_percentage" numeric(5,2) NOT NULL DEFAULT 0, "voucher_code" text, "voucher_discount_amount" numeric(12,2) DEFAULT 0, "total_stock_price" numeric(10,2) DEFAULT 0, "payment_id" bigint, "shipping_address_id" bigint, "user_id" bigint, CONSTRAINT "UQ_dc6871f2be6517ccdc4dd3a8e65" UNIQUE ("order_hash"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "orders_order_hash_key" ON "orders" ("order_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "orders_pkey" ON "orders" ("id") `);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" BIGSERIAL NOT NULL, "product_id" bigint NOT NULL, "user_id" bigint NOT NULL, "rating" bigint, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a3ec70bc6ddcdefb6c415bb05b8" UNIQUE ("product_id"), CONSTRAINT "UQ_f49ef8d0914a14decddbb170f2f" UNIQUE ("user_id"), CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ratings_product_id_user_id_key" ON "ratings" ("product_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ratings_pkey" ON "ratings" ("id") `);
        await queryRunner.query(`CREATE TABLE "vouchers" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "discount_amount" numeric(12,2) NOT NULL, "code" text NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "is_active" boolean DEFAULT true, CONSTRAINT "PK_ed1b7dd909a696560763acdbc04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "vouchers_pkey" ON "vouchers" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "vouchers_code_is_active_idx" ON "vouchers" ("code") `);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" text NOT NULL, "voucher_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "is_active" boolean DEFAULT true, "target_group_id" bigint, CONSTRAINT "UQ_5b2940ef338254b37caa10d12cd" UNIQUE ("voucher_id"), CONSTRAINT "REL_5b2940ef338254b37caa10d12c" UNIQUE ("voucher_id"), CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "campaigns_voucher_id_key" ON "campaigns" ("voucher_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "campaigns_pkey" ON "campaigns" ("id") `);
        await queryRunner.query(`CREATE TABLE "target_groups" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "filters" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_bda34fd7cb9b5a0c1b15cbd8719" UNIQUE ("name"), CONSTRAINT "PK_73042b184f2c7b5f2c2bf28311d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "target_groups_name_key" ON "target_groups" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "target_groups_pkey" ON "target_groups" ("id") `);
        await queryRunner.query(`CREATE TABLE "genders" ("id" BIGSERIAL NOT NULL, "type" text NOT NULL, CONSTRAINT "UQ_b91087eefc07cb873e61ae802d1" UNIQUE ("type"), CONSTRAINT "PK_529fb131dd4164c94529f53e19d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "genders_type_key" ON "genders" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "genders_pkey" ON "genders" ("id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" BIGSERIAL NOT NULL, "user_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "password_hash" text NOT NULL, "first_name" text NOT NULL, "last_name" text NOT NULL, "email" text NOT NULL, "phone" text NOT NULL, "address" text, "is_email_verified" boolean NOT NULL DEFAULT false, "has_first_login" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "birth_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "country_id" bigint, "gender_id" bigint, "iso_country_code_id" bigint, CONSTRAINT "UQ_ea60f106d908acd6f6bdfaf24cf" UNIQUE ("user_hash"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_user_hash_key" ON "users" ("user_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_pkey" ON "users" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_email_key" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" BIGSERIAL NOT NULL, "product_id" bigint NOT NULL, "user_id" bigint NOT NULL, "comment" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8f405e50bbc3adb9a80fac0f928" UNIQUE ("product_id"), CONSTRAINT "UQ_4c675567d2a58f0b07cef09c13d" UNIQUE ("user_id"), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "comments_product_id_user_id_key" ON "comments" ("product_id", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "comments_pkey" ON "comments" ("id") `);
        await queryRunner.query(`CREATE TABLE "images" ("id" BIGSERIAL NOT NULL, "url" text NOT NULL, "product_id" bigint, CONSTRAINT "PK_1fe148074c6a1a91b63cb9ee3c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "images_pkey" ON "images" ("id") `);
        await queryRunner.query(`CREATE TABLE "inventories" ("id" BIGSERIAL NOT NULL, "quantity" bigint NOT NULL, "product_id" bigint, CONSTRAINT "PK_7b1946392ffdcb50cfc6ac78c0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "inventories_pkey" ON "inventories" ("id") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "categories_pkey" ON "categories" ("id") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "price" numeric(12,2) NOT NULL, "short_description" text NOT NULL, "long_description" text NOT NULL, "code" text NOT NULL DEFAULT substring((uuid_generate_v4())::text, 1, 8), "stock_price" numeric(10,2) DEFAULT 0, CONSTRAINT "UQ_7cfc24d6c24f0ec91294003d6b8" UNIQUE ("code"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "products_pkey" ON "products" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "products_code_key" ON "products" ("code") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" BIGSERIAL NOT NULL, "cart_id" bigint NOT NULL, "product_id" bigint NOT NULL, "quantity" bigint NOT NULL, "unit_price" numeric(12,2) NOT NULL, "total_price" numeric(12,2), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6385a745d9e12a89b859bb25623" UNIQUE ("cart_id"), CONSTRAINT "UQ_30e89257a105eab7648a35c7fce" UNIQUE ("product_id"), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "cart_items_pkey" ON "cart_items" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "unique_cart_product" ON "cart_items" ("cart_id", "product_id") `);
        await queryRunner.query(`CREATE TABLE "carts" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "voucher_discount_amount" numeric(12,2) DEFAULT 0, "session_id" bigint, "user_id" bigint, "voucher_id" bigint, CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "carts_pkey" ON "carts" ("id") `);
        await queryRunner.query(`CREATE TABLE "session_types" ("id" BIGSERIAL NOT NULL, "type" text NOT NULL, CONSTRAINT "UQ_64dd7f225f2bb5511b1fbf354f7" UNIQUE ("type"), CONSTRAINT "PK_7d42a2ce4a75edfa6f9a8294cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "session_types_type_key" ON "session_types" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "session_types_pkey" ON "session_types" ("id") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" BIGSERIAL NOT NULL, "session_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "ip_address" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + '00:10:00'), "is_active" boolean NOT NULL DEFAULT true, "rate_limited_until" TIMESTAMP WITH TIME ZONE, "session_type_id" bigint, "user_id" bigint, CONSTRAINT "UQ_458f590ef250d670aff50570336" UNIQUE ("session_hash"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "sessions_session_hash_key" ON "sessions" ("session_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "sessions_pkey" ON "sessions" ("id") `);
        await queryRunner.query(`CREATE TABLE "failed_attempts" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "attempt_type_id" bigint, "session_id" bigint, CONSTRAINT "PK_07817f78b81d1b62a7dfd008f71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "failed_attempts_pkey" ON "failed_attempts" ("id") `);
        await queryRunner.query(`CREATE TABLE "attempt_types" ("id" BIGSERIAL NOT NULL, "type" text NOT NULL, CONSTRAINT "UQ_73f13312520c889aab3e0009fc5" UNIQUE ("type"), CONSTRAINT "PK_1618671e1c2786d7ca581759f0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "attempt_types_type_key" ON "attempt_types" ("type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "attempt_types_pkey" ON "attempt_types" ("id") `);
        await queryRunner.query(`CREATE TABLE "admin_failed_attempts" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "admin_session_id" bigint, "attempt_type_id" bigint, CONSTRAINT "PK_196deb1c2ae0fc9e48ac225029f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_failed_attempts_pkey" ON "admin_failed_attempts" ("id") `);
        await queryRunner.query(`CREATE TABLE "admin_sessions" ("id" BIGSERIAL NOT NULL, "session_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "ip_address" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() + '00:10:00'), "is_active" boolean NOT NULL DEFAULT true, "rate_limited_until" TIMESTAMP WITH TIME ZONE, "admin_user_id" bigint, "session_type_id" bigint, CONSTRAINT "UQ_c3dbf506f997ecf8da5e17fa153" UNIQUE ("session_hash"), CONSTRAINT "PK_38bb553c2372215d48de2306c5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_sessions_session_hash_key" ON "admin_sessions" ("session_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_sessions_pkey" ON "admin_sessions" ("id") `);
        await queryRunner.query(`CREATE TABLE "interfaces" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c5839f5f24f838c68efd19c220" UNIQUE ("name"), CONSTRAINT "PK_811ec6e568e3c1a89ac5e744731" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "interfaces_name_key" ON "interfaces" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "interfaces_pkey" ON "interfaces" ("id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "interface_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "UQ_18d2b2f184948e0cf69c8b55f71" UNIQUE ("interface_id"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "permissions_name_interface_id_key" ON "permissions" ("interface_id", "name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "permissions_pkey" ON "permissions" ("id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" bigint NOT NULL, "permission_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "role_permissions_pkey" ON "role_permissions" ("permission_id", "role_id") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_name_key" ON "roles" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "roles_pkey" ON "roles" ("id") `);
        await queryRunner.query(`CREATE TABLE "admin_user_roles" ("admin_user_id" bigint NOT NULL, "role_id" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5263f5c3644c00d0361d0f4a744" PRIMARY KEY ("admin_user_id", "role_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_user_roles_pkey" ON "admin_user_roles" ("admin_user_id", "role_id") `);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" BIGSERIAL NOT NULL, "user_hash" uuid NOT NULL DEFAULT uuid_generate_v4(), "password_hash" text NOT NULL, "first_name" text NOT NULL, "last_name" text NOT NULL, "email" text NOT NULL, "phone" text NOT NULL, "address" text, "is_email_verified" boolean NOT NULL DEFAULT false, "has_first_login" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "birth_date" date, "country_id" bigint, "gender_id" bigint, "iso_country_code_id" bigint, CONSTRAINT "UQ_63c0f138456376b97f2134499a0" UNIQUE ("user_hash"), CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_users_user_hash_key" ON "admin_users" ("user_hash") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_users_pkey" ON "admin_users" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "admin_users_active_email_idx" ON "admin_users" ("email") `);
        await queryRunner.query(`CREATE TABLE "iso_country_codes" ("id" BIGSERIAL NOT NULL, "country_name" text NOT NULL, "country_code" text NOT NULL, "phone_code" text NOT NULL, CONSTRAINT "UQ_c7ddf29c1cf8e4e534b55b6a8a1" UNIQUE ("country_name"), CONSTRAINT "UQ_4956d010f492e5e92dda0627486" UNIQUE ("country_code"), CONSTRAINT "PK_f93ab84e91b5c005b399235d5e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "iso_country_codes_pkey" ON "iso_country_codes" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "iso_country_codes_country_name_key" ON "iso_country_codes" ("country_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "iso_country_codes_country_code_key" ON "iso_country_codes" ("country_code") `);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" BIGSERIAL NOT NULL, "street" text NOT NULL, "city" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "country_id" bigint, "user_id" bigint, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "addresses_pkey" ON "addresses" ("id") `);
        await queryRunner.query(`CREATE TABLE "app_settings" ("id" BIGSERIAL NOT NULL, "request_limit" bigint NOT NULL DEFAULT 10, "request_window" interval NOT NULL DEFAULT '00:10:00', "request_block_duration" interval NOT NULL DEFAULT '01:00:00', "password_require_digit" boolean NOT NULL DEFAULT false, "password_require_lowercase" boolean NOT NULL DEFAULT false, "password_require_uppercase" boolean NOT NULL DEFAULT false, "password_require_special" boolean NOT NULL DEFAULT false, "vat_percentage" numeric(5,2) NOT NULL DEFAULT 0.00, "report_row_limit_display" bigint NOT NULL DEFAULT 1000, "campaign_status_update_interval" interval NOT NULL DEFAULT '00:05:00', "target_group_status_update_interval" interval NOT NULL DEFAULT '00:01:00', "target_group_status_update_initial_time" TIME WITH TIME ZONE NOT NULL DEFAULT '00:00:00+00', CONSTRAINT "PK_4800b266ba790931744b3e53a74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "app_settings_pkey" ON "app_settings" ("id") `);
        await queryRunner.query(`CREATE TABLE "emails" ("id" BIGSERIAL NOT NULL, "data_object" jsonb, "attempts" integer NOT NULL DEFAULT 0, "last_attempt" TIMESTAMP WITH TIME ZONE, "sent_at" TIMESTAMP WITH TIME ZONE, "status" text NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "error_type" text, "error" text, "priority" integer DEFAULT 5, "retry_after" TIMESTAMP WITH TIME ZONE, "processing_started_at" TIMESTAMP WITH TIME ZONE, "lock_id" uuid, "recipient_id" bigint, "recipient_email" text, "text_content" text, "subject" text, "type" text NOT NULL DEFAULT 'Email', "notification_id" bigint, CONSTRAINT "PK_a54dcebef8d05dca7e839749571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "emails_pkey" ON "emails" ("id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "user_ids" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "template_id" bigint, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "notifications_pkey" ON "notifications" ("id") `);
        await queryRunner.query(`CREATE TABLE "email_templates" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "subject" text NOT NULL, "placeholders" jsonb, "template" text, "table_border_width" bigint, "table_border_color" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" text NOT NULL DEFAULT 'Email', CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "email_templates_type_key" ON "email_templates" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "email_templates_type_unique" ON "email_templates" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "email_templates_pkey" ON "email_templates" ("id") `);
        await queryRunner.query(`CREATE TABLE "file_uploads" ("id" BIGSERIAL NOT NULL, "file_name" text NOT NULL, "file_path" text NOT NULL, "status" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ebfc99a8b660f0bc64a052b42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "file_uploads_pkey" ON "file_uploads" ("id") `);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "discount_percentage" numeric(5,2) NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_c1860010d8ccb782e747f0947e8" UNIQUE ("name"), CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "promotions_name_key" ON "promotions" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "promotions_pkey" ON "promotions" ("id") `);
        await queryRunner.query(`CREATE TABLE "user_target_groups" ("target_group_id" bigint NOT NULL, "user_id" bigint NOT NULL, CONSTRAINT "PK_605332a428c4a9091f191319f75" PRIMARY KEY ("target_group_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ecb17ef576921b115273fbea4" ON "user_target_groups" ("target_group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb15f326273582ff53a69f782c" ON "user_target_groups" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "voucher_usages" ("user_id" bigint NOT NULL, "voucher_id" bigint NOT NULL, CONSTRAINT "PK_0abeda7662b17cbcb5457c6693d" PRIMARY KEY ("user_id", "voucher_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fd46fe6fe9a3a3f11e59e717f4" ON "voucher_usages" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4bdf6ed30a785ef6ec68f8f3c5" ON "voucher_usages" ("voucher_id") `);
        await queryRunner.query(`CREATE TABLE "products_categories" ("category_id" bigint NOT NULL, "product_id" bigint NOT NULL, CONSTRAINT "PK_634f5e1b5983772473fe0ec0008" PRIMARY KEY ("category_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_19fe0fe8c2fcf1cbe1a80f639f" ON "products_categories" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2c76a4306a82c696d620f81f0" ON "products_categories" ("product_id") `);
        await queryRunner.query(`ALTER TABLE "admin_captchas" ADD CONSTRAINT "FK_448dcd4af7cb56bc422f6b26153" FOREIGN KEY ("admin_session_id") REFERENCES "admin_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "captchas" ADD CONSTRAINT "FK_e991ec4cdb6148372daf81ef41e" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verifications" ADD CONSTRAINT "FK_c4f1838323ae1dff5aa00148915" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logs" ADD CONSTRAINT "FK_29252511031c24436e309148498" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logs" ADD CONSTRAINT "FK_70c2c3d40d9f661ac502de51349" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_5b3e94bd2aedc184f9ad8c10439" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_67b8be57fc38bda573d2a8513ec" FOREIGN KEY ("shipping_address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_a3ec70bc6ddcdefb6c415bb05b8" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_f49ef8d0914a14decddbb170f2f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_5b1b71ad45c48e5342eed4e1413" FOREIGN KEY ("target_group_id") REFERENCES "target_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaigns" ADD CONSTRAINT "FK_5b2940ef338254b37caa10d12cd" FOREIGN KEY ("voucher_id") REFERENCES "vouchers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_ae78dc6cb10aa14cfef96b2dd90" FOREIGN KEY ("country_id") REFERENCES "iso_country_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_7fc7be0985c48fa965c80fc8775" FOREIGN KEY ("gender_id") REFERENCES "genders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_7e0e5fda57cd91d4efaab039e6b" FOREIGN KEY ("iso_country_code_id") REFERENCES "iso_country_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8f405e50bbc3adb9a80fac0f928" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "images" ADD CONSTRAINT "FK_96fabbb1202770b8e6a58bf6f1d" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_92fc0c77bab4a656b9619322c62" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_6385a745d9e12a89b859bb25623" FOREIGN KEY ("cart_id") REFERENCES "carts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_30e89257a105eab7648a35c7fce" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_f57f87515b7c25718dc380c69c7" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_c879a28f2b82295b04bcb946801" FOREIGN KEY ("voucher_id") REFERENCES "vouchers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_192fb44c16c080b3c487c8070f7" FOREIGN KEY ("session_type_id") REFERENCES "session_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "failed_attempts" ADD CONSTRAINT "FK_13652980e2316a68df1cfa27d82" FOREIGN KEY ("attempt_type_id") REFERENCES "attempt_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "failed_attempts" ADD CONSTRAINT "FK_ea9668ac05965272a731863205c" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_failed_attempts" ADD CONSTRAINT "FK_ca2bc0367da4f60f1ff39d577d9" FOREIGN KEY ("admin_session_id") REFERENCES "admin_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_failed_attempts" ADD CONSTRAINT "FK_5ad354b3748bb4c9fe46329b5d7" FOREIGN KEY ("attempt_type_id") REFERENCES "attempt_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" ADD CONSTRAINT "FK_c1711b1831bdf66b77c3605bcdb" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" ADD CONSTRAINT "FK_4033b2eb4146cdb4135e1a2a574" FOREIGN KEY ("session_type_id") REFERENCES "session_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_18d2b2f184948e0cf69c8b55f71" FOREIGN KEY ("interface_id") REFERENCES "interfaces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_user_roles" ADD CONSTRAINT "FK_9617e2389b6171beba70c337d48" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_user_roles" ADD CONSTRAINT "FK_cd6367a2354fe9d84225ada5baf" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "FK_f348d678df586563f3e01dd3c55" FOREIGN KEY ("country_id") REFERENCES "iso_country_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "FK_5cfc69a78307e1bb67fcf1764fa" FOREIGN KEY ("gender_id") REFERENCES "genders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "FK_4a474892246b189ed878a3783b6" FOREIGN KEY ("iso_country_code_id") REFERENCES "iso_country_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_98e1ca336038167c7eb48c02582" FOREIGN KEY ("country_id") REFERENCES "iso_country_codes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emails" ADD CONSTRAINT "FK_cba1dce3b583d27676f9f99b8d9" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_e37d0438b1fffd0f210df30b271" FOREIGN KEY ("template_id") REFERENCES "email_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_target_groups" ADD CONSTRAINT "FK_6ecb17ef576921b115273fbea43" FOREIGN KEY ("target_group_id") REFERENCES "target_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_target_groups" ADD CONSTRAINT "FK_cb15f326273582ff53a69f782c8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "voucher_usages" ADD CONSTRAINT "FK_fd46fe6fe9a3a3f11e59e717f48" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "voucher_usages" ADD CONSTRAINT "FK_4bdf6ed30a785ef6ec68f8f3c55" FOREIGN KEY ("voucher_id") REFERENCES "vouchers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_categories" ADD CONSTRAINT "FK_19fe0fe8c2fcf1cbe1a80f639f1" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_categories" ADD CONSTRAINT "FK_f2c76a4306a82c696d620f81f08" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "products_categories" DROP CONSTRAINT "FK_f2c76a4306a82c696d620f81f08"`);
        await queryRunner.query(`ALTER TABLE "products_categories" DROP CONSTRAINT "FK_19fe0fe8c2fcf1cbe1a80f639f1"`);
        await queryRunner.query(`ALTER TABLE "voucher_usages" DROP CONSTRAINT "FK_4bdf6ed30a785ef6ec68f8f3c55"`);
        await queryRunner.query(`ALTER TABLE "voucher_usages" DROP CONSTRAINT "FK_fd46fe6fe9a3a3f11e59e717f48"`);
        await queryRunner.query(`ALTER TABLE "user_target_groups" DROP CONSTRAINT "FK_cb15f326273582ff53a69f782c8"`);
        await queryRunner.query(`ALTER TABLE "user_target_groups" DROP CONSTRAINT "FK_6ecb17ef576921b115273fbea43"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_e37d0438b1fffd0f210df30b271"`);
        await queryRunner.query(`ALTER TABLE "emails" DROP CONSTRAINT "FK_cba1dce3b583d27676f9f99b8d9"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_16aac8a9f6f9c1dd6bcb75ec023"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_98e1ca336038167c7eb48c02582"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "FK_4a474892246b189ed878a3783b6"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "FK_5cfc69a78307e1bb67fcf1764fa"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "FK_f348d678df586563f3e01dd3c55"`);
        await queryRunner.query(`ALTER TABLE "admin_user_roles" DROP CONSTRAINT "FK_cd6367a2354fe9d84225ada5baf"`);
        await queryRunner.query(`ALTER TABLE "admin_user_roles" DROP CONSTRAINT "FK_9617e2389b6171beba70c337d48"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_18d2b2f184948e0cf69c8b55f71"`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" DROP CONSTRAINT "FK_4033b2eb4146cdb4135e1a2a574"`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" DROP CONSTRAINT "FK_c1711b1831bdf66b77c3605bcdb"`);
        await queryRunner.query(`ALTER TABLE "admin_failed_attempts" DROP CONSTRAINT "FK_5ad354b3748bb4c9fe46329b5d7"`);
        await queryRunner.query(`ALTER TABLE "admin_failed_attempts" DROP CONSTRAINT "FK_ca2bc0367da4f60f1ff39d577d9"`);
        await queryRunner.query(`ALTER TABLE "failed_attempts" DROP CONSTRAINT "FK_ea9668ac05965272a731863205c"`);
        await queryRunner.query(`ALTER TABLE "failed_attempts" DROP CONSTRAINT "FK_13652980e2316a68df1cfa27d82"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_192fb44c16c080b3c487c8070f7"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_c879a28f2b82295b04bcb946801"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_2ec1c94a977b940d85a4f498aea"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_f57f87515b7c25718dc380c69c7"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_30e89257a105eab7648a35c7fce"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_6385a745d9e12a89b859bb25623"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_92fc0c77bab4a656b9619322c62"`);
        await queryRunner.query(`ALTER TABLE "images" DROP CONSTRAINT "FK_96fabbb1202770b8e6a58bf6f1d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8f405e50bbc3adb9a80fac0f928"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_7e0e5fda57cd91d4efaab039e6b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_7fc7be0985c48fa965c80fc8775"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_ae78dc6cb10aa14cfef96b2dd90"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_5b2940ef338254b37caa10d12cd"`);
        await queryRunner.query(`ALTER TABLE "campaigns" DROP CONSTRAINT "FK_5b1b71ad45c48e5342eed4e1413"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_f49ef8d0914a14decddbb170f2f"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_a3ec70bc6ddcdefb6c415bb05b8"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_67b8be57fc38bda573d2a8513ec"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_5b3e94bd2aedc184f9ad8c10439"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "logs" DROP CONSTRAINT "FK_70c2c3d40d9f661ac502de51349"`);
        await queryRunner.query(`ALTER TABLE "logs" DROP CONSTRAINT "FK_29252511031c24436e309148498"`);
        await queryRunner.query(`ALTER TABLE "email_verifications" DROP CONSTRAINT "FK_c4f1838323ae1dff5aa00148915"`);
        await queryRunner.query(`ALTER TABLE "captchas" DROP CONSTRAINT "FK_e991ec4cdb6148372daf81ef41e"`);
        await queryRunner.query(`ALTER TABLE "admin_captchas" DROP CONSTRAINT "FK_448dcd4af7cb56bc422f6b26153"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2c76a4306a82c696d620f81f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19fe0fe8c2fcf1cbe1a80f639f"`);
        await queryRunner.query(`DROP TABLE "products_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bdf6ed30a785ef6ec68f8f3c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd46fe6fe9a3a3f11e59e717f4"`);
        await queryRunner.query(`DROP TABLE "voucher_usages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb15f326273582ff53a69f782c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ecb17ef576921b115273fbea4"`);
        await queryRunner.query(`DROP TABLE "user_target_groups"`);
        await queryRunner.query(`DROP INDEX "public"."promotions_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."promotions_name_key"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP INDEX "public"."file_uploads_pkey"`);
        await queryRunner.query(`DROP TABLE "file_uploads"`);
        await queryRunner.query(`DROP INDEX "public"."email_templates_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."email_templates_type_unique"`);
        await queryRunner.query(`DROP INDEX "public"."email_templates_type_key"`);
        await queryRunner.query(`DROP TABLE "email_templates"`);
        await queryRunner.query(`DROP INDEX "public"."notifications_pkey"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."emails_pkey"`);
        await queryRunner.query(`DROP TABLE "emails"`);
        await queryRunner.query(`DROP INDEX "public"."app_settings_pkey"`);
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP INDEX "public"."addresses_pkey"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP INDEX "public"."iso_country_codes_country_code_key"`);
        await queryRunner.query(`DROP INDEX "public"."iso_country_codes_country_name_key"`);
        await queryRunner.query(`DROP INDEX "public"."iso_country_codes_pkey"`);
        await queryRunner.query(`DROP TABLE "iso_country_codes"`);
        await queryRunner.query(`DROP INDEX "public"."admin_users_active_email_idx"`);
        await queryRunner.query(`DROP INDEX "public"."admin_users_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."admin_users_user_hash_key"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP INDEX "public"."admin_user_roles_pkey"`);
        await queryRunner.query(`DROP TABLE "admin_user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."roles_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."roles_name_key"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."role_permissions_pkey"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."permissions_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."permissions_name_interface_id_key"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."interfaces_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."interfaces_name_key"`);
        await queryRunner.query(`DROP TABLE "interfaces"`);
        await queryRunner.query(`DROP INDEX "public"."admin_sessions_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."admin_sessions_session_hash_key"`);
        await queryRunner.query(`DROP TABLE "admin_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."admin_failed_attempts_pkey"`);
        await queryRunner.query(`DROP TABLE "admin_failed_attempts"`);
        await queryRunner.query(`DROP INDEX "public"."attempt_types_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."attempt_types_type_key"`);
        await queryRunner.query(`DROP TABLE "attempt_types"`);
        await queryRunner.query(`DROP INDEX "public"."failed_attempts_pkey"`);
        await queryRunner.query(`DROP TABLE "failed_attempts"`);
        await queryRunner.query(`DROP INDEX "public"."sessions_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."sessions_session_hash_key"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."session_types_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."session_types_type_key"`);
        await queryRunner.query(`DROP TABLE "session_types"`);
        await queryRunner.query(`DROP INDEX "public"."carts_pkey"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP INDEX "public"."unique_cart_product"`);
        await queryRunner.query(`DROP INDEX "public"."cart_items_pkey"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."products_code_key"`);
        await queryRunner.query(`DROP INDEX "public"."products_pkey"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."categories_pkey"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."inventories_pkey"`);
        await queryRunner.query(`DROP TABLE "inventories"`);
        await queryRunner.query(`DROP INDEX "public"."images_pkey"`);
        await queryRunner.query(`DROP TABLE "images"`);
        await queryRunner.query(`DROP INDEX "public"."comments_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."comments_product_id_user_id_key"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."users_email_key"`);
        await queryRunner.query(`DROP INDEX "public"."users_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."users_user_hash_key"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."genders_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."genders_type_key"`);
        await queryRunner.query(`DROP TABLE "genders"`);
        await queryRunner.query(`DROP INDEX "public"."target_groups_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."target_groups_name_key"`);
        await queryRunner.query(`DROP TABLE "target_groups"`);
        await queryRunner.query(`DROP INDEX "public"."campaigns_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."campaigns_voucher_id_key"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."vouchers_code_is_active_idx"`);
        await queryRunner.query(`DROP INDEX "public"."vouchers_pkey"`);
        await queryRunner.query(`DROP TABLE "vouchers"`);
        await queryRunner.query(`DROP INDEX "public"."ratings_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."ratings_product_id_user_id_key"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP INDEX "public"."orders_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."orders_order_hash_key"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."payments_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."payments_order_id_key"`);
        await queryRunner.query(`DROP INDEX "public"."payments_payment_hash_key"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."order_items_pkey"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."logs_pkey"`);
        await queryRunner.query(`DROP TABLE "logs"`);
        await queryRunner.query(`DROP INDEX "public"."email_verifications_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."email_verifications_token_hash_key"`);
        await queryRunner.query(`DROP TABLE "email_verifications"`);
        await queryRunner.query(`DROP INDEX "public"."captchas_pkey"`);
        await queryRunner.query(`DROP TABLE "captchas"`);
        await queryRunner.query(`DROP INDEX "public"."admin_captchas_pkey"`);
        await queryRunner.query(`DROP TABLE "admin_captchas"`);
    }

}