const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 1,
  UNAUTHORIZED: 2,
  INVALID_SESSION: 3,
  INVALID_LOGIN: 4,
  INVALID_TOKEN: 5,
  INVALID_INPUT: 6,
  INVALID_BODY: 7,
  INVALID_QUERY_PARAMS: 8,
  WRONG_PASSWORD: 9,
  RATE_LIMITED: 10,
  NO_CHANGES: 11,
  DUPLICATE: 12,
  NOT_FOUND: 13,
};

module.exports = ERROR_CODES;